[package]
name = "PONG"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
vek = "0.17.2"
lerp = "0.5.0"
font8x8 = "0.3.1"
rodio = "0.21.1"

[build-dependencies]
winres = "0.1.12"
